apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  namespace: default
spec:
  capacity:
    storage: 100Mi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/log"
  persistentVolumeReclaimPolicy: Retain